version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ".tmp/redis/setlister/data:/data"
    command: redis-server --appendonly yes
    environment:
      - REDIS_PASSWORD=

  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - ".tmp/mysql/setlister/data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=setlister
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      
