version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ".tmp/redis/setlister/data:/data"
    command: redis-server --appendonly yes
    environment:
      - REDIS_PASSWORD=password
